FROM node:16

WORKDIR /server

COPY package*.json ./

RUN npm install

RUN apt-get update && apt-get install -y gnupg
RUN wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add -
RUN echo "deb http://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-6.0.list
RUN apt-get update && apt-get install -y mongodb-org-tools=6.0.0

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start"]
