# Use a base Node.js image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the backend server code
COPY . .

# Expose the port on which your backend server runs
EXPOSE 3000

# Specify the command to start the server

